blank_issues_enabled: false
contact_links:
  - name: OpenZFS Community Support Mailing list
    url: https://openzfs.topicbox.com/groups/discuss
    about: Get community support for OpenZFS
  - name: OpenZFS on IRC
    url: https://webchat.freenode.net/#openzfs
    about: Use IRC to get community support for OpenZFS
